# Generated by Django 5.0.3 on 2024-03-13 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
